### ISSUE TITLE
Kernel Panic on macOS Catalina 10.15 Beta1 (19A471t)

### ISSUE THREAD

**Issue by williambj1** [Goldfish64/SystemProfilerMemoryFixup#1]
First of, thanks for providing such a kext for showing memory slots. I really like this feature.

After upgrading to macOS Catalina 10.15 Beta1 (19A471t) this kext causes a kernel panic during the system startup.

I've already used `LiluBetaall` to force all plugins to load.

I'll upload an image of the panic later.

Hope this issue will be solved soon. 

Thank you very much!

**Comment by Goldfish64** [comment]
I can look into it. Would you be able to provide a screenshot of the panic?

**Comment by anonymous-writer** [comment]
Not so easy. Have created a movie.
[IMG_0710.mp4.zip](https://github.com/Goldfish64/SystemProfilerMemoryFixup/files/3322185/IMG_0710.mp4.zip)

**Comment by Goldfish64** [comment]
Should be fixed with 16689b8.

**Comment by anonymous-writer** [comment]
Works now great under Catalina. Thank you for your work.
