### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by HelmoHass** [Goldfish64/SystemProfilerMemoryFixup#2]
Hi.
just wanted to report that the plugin fail to build with new version of Lilu 1.4.0

tested with version 1.3.9 and it build successfully...
[SystemProfilerMemoryFixup.log](https://github.com/Goldfish64/SystemProfilerMemoryFixup/files/3893638/SystemProfilerMemoryFixup.log)

**Comment by Goldfish64** [comment]
Should be fixed. Thanks.
