### ISSUE TITLE
MacProMemoryNotificationDisabler

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [Goldfish64/SystemProfilerMemoryFixup#3]
Look https://github.com/IOIIIO/MacProMemoryNotificationDisabler
Maybe you will add it in the SystemProfilerMemoryFixup?

**Comment by maojinbing** [comment]
https://github.com/IOIIIO/MacProMemoryNotificationDisabler/issues/4

I still have no clue what the relation between WEG and this kext is？
